[board]
name   = "BBC micro:bit v2"
chip   = "nRF52833_xxAA"
target = "thumbv7em-none-eabihf"
elf    = "<CRATE_NAME>"

[probe]
protocol = "swd"
speed    = 4000          # kHz

[flash]
restore_unwritten = false
halt_afterwards   = false

[rtt]
enabled  = true
channels = [{ up = 0, name = "Terminal" }]

# ---------------------------------------------------------------------------
# [new_project] — files and settings scaffolded when creating a new project
# ---------------------------------------------------------------------------
[new_project]
runner = "probe-rs run --chip nRF52833_xxAA --protocol swd"

dependencies = '''
cortex-m         = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt      = "0.7"
microbit-v2      = "0.16"
panic-rtt-target = "0.2"
rtt-target       = "0.6"
'''

[[new_project.files]]
path              = "rustdyno.toml"
replace_if_exists = true
content = '''
default="microbit-v2.toml"
'''

[[new_project.files]]
path              = "Embed.toml"
replace_if_exists = true
content = '''
[default.general]
chip = "nrf52833_xxAA"

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true

[default.gdb]
enabled = false
'''

[[new_project.files]]
path    = "src/main.rs"
content = '''
#![no_main]
#![no_std]

use panic_rtt_target as _;
use rtt_target::{rprintln, rtt_init_print};

use cortex_m_rt::entry;
use microbit::board::Board;

#[entry]
fn main() -> ! {
    rtt_init_print!();
    let _board = Board::take().unwrap();
    let mut counter = 0u64;
    loop {
        rprintln!("{}", counter);
        counter += 1;
    }
}
'''

[[new_project.files]]
path              = ".cargo/config.toml"
replace_if_exists = true
content = '''
[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52833_xxAA --protocol {{PROTOCOL}}"
rustflags = [
  "-C", "linker=rust-lld",
  "-C", "link-arg=-Tlink.x",
]
'''
